# Generated by Django 3.1.7 on 2021-03-18 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0002_auto_20210318_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
