# Generated by Django 3.1.7 on 2021-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0003_auto_20210318_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
